name: CI/CD

permissions:
  contents: write
  actions: read

on:
  push:
    branches:
      - 'main'

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: nodejs
  IMAGE_TAG: node-hello-app
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - uses: super-linter/super-linter@v5.7.2
        name: Super-Linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main  
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_YAML: false

  build:
    runs-on: ubuntu-latest
    needs: linting
    outputs:
      image_uri: ${{ steps.image.outputs.image_uri }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to ECR
        id: image 
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          IMAGE_URI=$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

          echo "Building image: $IMAGE_URI"
          docker build -t $IMAGE_URI .

          echo "Pushing image to ECR"
          docker push $IMAGE_URI

          # Save the image URI as output
          echo "::set-output name=image_uri::$IMAGE_URI"

      - name: passing image name
        run: |
          sed -i "s#IMAGE#$IMAGE_URI#g" ../terraform/terraform.tfvars
  
      - uses: stefanzweifel/git-auto-commit-action@v5
        name: commit changes

  deploy:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: terraform/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply --auto-approve

  set:
    runs-on: ubuntu-latest
    needs: deploy
    defaults:
      run:
        working-directory: terraform/
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: setting image to default for future runs
        run: |
          IMAGE_URI=${{ needs.build.outputs.image_uri }}
          sed -i "s#$IMAGE_URI#IMAGE#g terraform.tfvars

      - uses: stefanzweifel/git-auto-commit-action@v5
        name: commit changes
